export const APP_TIMEOUT = 120 * 1000; // 최대 2분

// TODO: 추후 변경
export const INFLUENCER_LIST = [
  'henrychang10000',
  'elonmusk',
  'VitalikButerin',
  'jessepollak',
  'realDonaldTrump',
  'brian_armstrong',
  'cdixon',
  'cz_binance',
  'aixbt_agent',
  'saylor',
  'aantonop',
  'RaoulGMI',
  'haydenzadams',
  'ErikVoorhees',
  'sassal0x',
  'BanklessHQ',
  'coinbureau',
  'TheCryptoDog',
  'jchervinsky',
  'MessariCrypto',
  'animocabrands',
  'gabusch',
  'Immutable',
  'punk6529',
  '0xPolygon',
  'WAX_io',
  'EllioTrades',
  'Brycent_',
  'Cagyjan1',
];
